name: VK to Telegram Reposter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  repost:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run reposter
        run: echo "Тест"
